name: garage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  icons_launcher: ^3.0.3
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/home.jpg
    - assets/logo.png
    - assets/user.webp
    - assets/admin.jpg
